version: '3'

services:
  workspace:
    image: node:16-bullseye
    network_mode: "host"
    working_dir: /workspace
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ../:/workspace:cached
    tty: true
